name: Test Package
on: [push]

jobs:
  test:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [ 12.x , 10.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}
      - name: Setup memcached
        uses: KeisukeYamashita/memcached-actions@v1
        with:
          ports: "11211,11212,11213"
      - run: yarn
      - run: yarn test
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
